export const MenuItems = [
    'Market',
    'Messenger',
    'Project Timer',
    'To-do Timer',
    'Timers',
    'World Time',
    'Metronome',
    'Stress Test',
    'Pomodoro',
    'Alarm Clock',
    'Calendar',
    'Time Together',
    'Jihad Bakkoura',
    'Family Tree',
    'Bakkoura Watch',
    'Time Clinic',
    'Time Biotic',
    'Time Management',
    'Podcasts',
    '30h Legend',
    'Assestment Watch',
    'Watch Constructor',
    'Send Your Idea',
    'About Time',
    'FrankVila Watch',
    'Walpapers',
    'Contact Us',
    'BTS navigation',
    'Time Wealth',
    'Reccomendations',
]