import {ConstructorSvgs} from '../assets/constructor';

export const WatchConstrctorData = {
  bodyTypes: [
    ConstructorSvgs.bodyType1,
    ConstructorSvgs.bodyType2,
    ConstructorSvgs.bodyType3,
    ConstructorSvgs.bodyType4,
    ConstructorSvgs.bodyType5,
    ConstructorSvgs.bodyType6,
    ConstructorSvgs.bodyType7,
    ConstructorSvgs.bodyType8,
    ConstructorSvgs.bodyType9,
    ConstructorSvgs.bodyType10,
    ConstructorSvgs.bodyType11,
    ConstructorSvgs.bodyType12,
    ConstructorSvgs.bodyType13,
  ],
  backStyles: [
    ConstructorSvgs.backStyle1,
    ConstructorSvgs.backStyle2,
    ConstructorSvgs.backStyle3,
    ConstructorSvgs.backStyle4,
    ConstructorSvgs.backStyle5,
    ConstructorSvgs.backStyle6,
    ConstructorSvgs.backStyle7,
    ConstructorSvgs.backStyle8,
    ConstructorSvgs.backStyle9,
    ConstructorSvgs.backStyle10,
    ConstructorSvgs.backStyle11,
    ConstructorSvgs.backStyle12,
  ],
  faceTypes: [
    ConstructorSvgs.face1,
    ConstructorSvgs.face2,
    ConstructorSvgs.face3,
    ConstructorSvgs.face4,
    ConstructorSvgs.face5,
    ConstructorSvgs.face6,
    ConstructorSvgs.face7,
    ConstructorSvgs.face8,
    ConstructorSvgs.face9,
    ConstructorSvgs.face10,
    ConstructorSvgs.face11,
    ConstructorSvgs.face12,
  ],
  options: [
    ConstructorSvgs.option1,
    ConstructorSvgs.option2,
    ConstructorSvgs.option3,
    ConstructorSvgs.option4,
    ConstructorSvgs.option5,
    ConstructorSvgs.option6,
    ConstructorSvgs.option7,
    ConstructorSvgs.option8,
    ConstructorSvgs.option9,
    ConstructorSvgs.option10,
    ConstructorSvgs.option11,
    ConstructorSvgs.option12,
  ],
  numbers: [
    ConstructorSvgs.number1,
    ConstructorSvgs.number2,
    ConstructorSvgs.number3,
    ConstructorSvgs.number4,
    ConstructorSvgs.number5,
    ConstructorSvgs.number6,
    ConstructorSvgs.number7,
    ConstructorSvgs.number8,
    ConstructorSvgs.number9,
    ConstructorSvgs.number10,
    ConstructorSvgs.number11,
    ConstructorSvgs.number12,
  ],
  arrows: [
    ConstructorSvgs.arrows1,
    ConstructorSvgs.arrows2,
    ConstructorSvgs.arrows3,
    ConstructorSvgs.arrows4,
    ConstructorSvgs.arrows5,
    ConstructorSvgs.arrows6,
    ConstructorSvgs.arrows7,
    ConstructorSvgs.arrows8,
    ConstructorSvgs.arrows9,
    ConstructorSvgs.arrows10,
    ConstructorSvgs.arrows11,
    ConstructorSvgs.arrows12,
    ConstructorSvgs.arrows13,
  ],
};

export const ConstructorParts = [
  {
    key: 'bodyTypes',
    title: 'Body Type',
  },
  {
    key: 'faceTypes',
    title: 'Clock face Type',
  },
  {
    key: 'arrows',
    title: 'Arrows Type',
  },
  {
    key: 'numbers',
    title: 'Numbers Type',
  },
  {
    key: 'backStyles',
    title: 'Background Style',
  },
  {
    key: 'options',
    title: 'Add. Options',
  },
];
