export const Lotties = {
  calendarLoading: require('./calendarLoading.json'),
  waweLoading: require('./waweLoading.json'),
  loading: require('./loading.json'),
  pomodoro: require('./AnimLinear-1.json'),
  timer: require('./AnimLinear-2.json'),
  stressTest: require('./AnimLinear-3.json'),
  timeTogether: require('./AnimLinear-4.json'),
  clock: require('./CLOCK.json'),
  goldHeart: require('./gold-heart-2.json'),
  whiteClock: require('./whiteClock.json'),
  whiteHeart: require('./whiteHeart.json'),
  whitePanda: require('./whitePanda.json'),
  whiteTomato: require('./whiteTomato.json'),
  whiteShape: require('./whiteShape.json'),
};
