import {
  TouchableOpacity,
  Pressable,
  StyleSheet,
  Platform,
  TextInput,
  Image,
  ImageBackground,
  FlatList,
  Animated,
  ScrollView,
  Modal,
  Dimensions,
  Button,
  StatusBar,
  Alert,
  Share,
  TouchableWithoutFeedback,
} from 'react-native';
import View from './View';
import Text from './Text';
import { SafeAreaView } from 'react-native-safe-area-context';

export default {
  TouchableOpacity,
  Pressable,
  StyleSheet,
  Platform,
  TextInput,
  Image,
  ImageBackground,
  FlatList,
  Animated,
  ScrollView,
  Modal,
  Dimensions,
  Button,
  StatusBar,
  Alert,
  View,
  Text,
  Share,
  SafeAreaView,
  TouchableWithoutFeedback,
};
